# Generated by Django 3.2 on 2021-05-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
                ('mdcn', models.IntegerField(unique=True, verbose_name='MDCN Number')),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dental specialist', 'Dental specialist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('family medicine', 'family medicine'), ('Gastroenterology & Hepatologist', 'Gastroenterology & Hepatologist'), ('General Dentist', 'General Dentist'), ('General medicine', 'General medicine'), ('Geriatrician', 'Geriatrician'), ('Hematology', 'Hematology'), ('Infectious disease', 'Infectious disease'), ('Nephrologist', 'Nephrologist'), ('Neurologist', 'Neurologist'), ('Nuclear Physician ', 'Nuclear Physician '), ('Oncologist', 'Oncologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Paediatrician', 'Paediatrician'), ('Pain physician', 'Pain physician'), ('Radiologist', 'Radiologist'), ('Radiotherapist', 'Radiotherapist'), ('Rheumatologist', 'Rheumatologist'), ('Urologist', 'Urologist'), ('Cardiothoracic & vascular surgery', 'Cardiothoracic & vascular surgery'), ('Dental Surgeon', 'Dental Surgeon'), ('ENT surgeon', 'ENT surgeon'), ('General surgeon', 'General surgeon'), ('Neurosurgeon', 'Neurosurgeon'), ('Orthopedics & Trauma surgeon', 'Orthopedics & Trauma surgeon'), ('Paediatric surgeon', 'Paediatric surgeon'), ('Plastic & Cosmetic Surgeon', 'Plastic & Cosmetic Surgeon'), ('Obstetrics & Gynecologist', 'Obstetrics & Gynecologist'), ('Psychiatrist', 'Psychiatrist')], max_length=50, verbose_name='Specialization')),
                ('language', models.CharField(max_length=50, verbose_name='Languages you can consult with')),
                ('agreement', models.BooleanField(default=False, verbose_name='terms and conditions')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.customuser',),
        ),
    ]
