# Generated by Django 3.2 on 2021-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210505_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mdcn',
            field=models.IntegerField(verbose_name='MDCN Number'),
        ),
    ]
