# Generated by Django 3.2 on 2021-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_mdcn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='language',
            field=models.JSONField(),
        ),
    ]
