# Generated by Django 3.2 on 2021-05-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('slug', models.SlugField(default='slug')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='gender')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone number')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('user_type', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10, null=True, verbose_name='User Type')),
                ('is_staff', models.BooleanField(default=False, verbose_name='admin staff ?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('phone', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
                ('blood_group', models.CharField(max_length=10, verbose_name='Blood group')),
                ('genotype', models.CharField(max_length=2, verbose_name='Genotype')),
                ('height', models.IntegerField(verbose_name='Height(Meters)')),
                ('weight', models.IntegerField(verbose_name='Weight(lbs)')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.customuser',),
        ),
    ]
